server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: kps-libro-service
          uri: lb://kps-libro-service
          predicates:
            - Path=/libros/**
        - id: kps-usuario-service
          uri: lb://kps-usuario-service
          predicates:
            - Path=/usuarios/**
        - id: kps-prestamo-service
          uri: lb://kps-prestamo-service
          predicates:
            - Path=/prestamos/**
